version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: '5432'
      DATABASE_USER: todo_user
      DATABASE_PASSWORD: todo_pass
      DATABASE_NAME: todo_db
    ports:
      - "7000:7000"

  ui:
    build: ./ui
    depends_on:
      - api
    ports:
      - "7001:80"

volumes:
  db-data:
