apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: kubernetes-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_USER
              value: "todo_user"
            - name: DATABASE_PASSWORD
              value: "todo_pass"
            - name: DATABASE_NAME
              value: "todo_db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_HOST
              value: "db"
          # resource requests so HPA/metrics can react
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/todos/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/todos/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
